CREATE TABLE IF NOT EXISTS child AS SELECT * FROM child WHERE childid > 12;
CREATE TABLE IF NOT EXISTS child AS SELECT * FROM child;
CREATE TABLE IF NOT EXISTS child AS SELECT * FROM child WHERE childid > 12;
